version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/hackertracker.info
    steps:
      - checkout
      - run:
          name: install awscli
          command: sudo pip install awscli
      - run:
          name: remove .git and .circleci
          command: rm -rf .git && rm -rf .gitignore && rm -rf .circleci
      - run:
          name: deploy to S3
          command: aws s3 sync . s3://hackertracker.info/ --region us-east-1 --acl public-read
